home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [	
	url(r'^$', views.index),
	url(r'^about/$', views.about),
	url(r'^service_3pl/$', views.service_3pl),
	url(r'^service_it/$', views.service_it),
	url(r'^contactus/$', views.contactus),
	url(r'^account/$', views.account),
]

materials/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^c/(\d+)/$', views.index_detail, name='index_c'),

	url(r'^incoming/$', views.incoming, name='incoming'),
	url(r'^incoming/p(\d+)', views.incoming_pallet, name="incoming_p"),
	url(r'^incoming/c(\d+)', views.incoming_customer, name="incoming_c"),
	url(r'^incoming/z(\d+)', views.incoming_zone, name="incoming_z"),
	url(r'^incoming/m(\d+)', views.incoming_material, name="incoming_m"),

	url(r'^outgoing/$', views.outgoing, name='outgoing'),
	url(r'^outgoing/p(\d+)', views.outgoing_pallet, name="outgoing_p"),
	url(r'^outgoing/c(\d+)', views.outgoing_customer, name="outgoing_c"),
	url(r'^outgoing/z(\d+)', views.outgoing_zone, name="outgoing_z"),
	url(r'^outgoing/m(\d+)', views.outgoing_material, name="outgoing_m"),

	url(r'^result/$', views.result, name='result'),
	url(r'^result/c(\d+)', views.result, name='result_c'),
	url(r'^result/m(\d+)', views.result_detail, name='result_detail'),

	# url(r'^work/incoming/$', views.incoming_form.as_view(), name = 'work_incoming'),
	url(r'^work/incoming/$', views.incoming_form, name = 'work_incoming'),
	url(r'^incoming/edit(?P<pk>[0-9]+)', views.incoming_edit, name = 'work_incoming_edit'),
	# url(r'^work/outgoing/$', views.outgoing_form.as_view(), name = 'work_outgoing'),
	url(r'^work/outgoing/$', views.outgoing_form, name = 'work_outgoing'),
	url(r'^outgoing/edit(?P<pk>[0-9]+)', views.outgoing_edit, name = 'work_outgoing_edit'),

]

woochang_erp/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

urlpatterns = [    
    url(r'^', include('home.urls', namespace="home")),
    url(r'^admin/', include(admin.site.urls)),    
    url(r'^materials/', include('materials.urls', namespace="materials")),
    url(r'^customers/', include('customers.urls', namespace="customers")),    
]

customers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
	user = models.OneToOneField(User)
	customer_name = models.CharField(max_length = 60)
	manager = models.CharField(max_length = 12, blank = True)
	telephone_1 = models.CharField(max_length = 20, blank = True)
	telephone_2 = models.CharField(max_length = 20, blank = True)
	fax = models.CharField(max_length = 20, blank = True)
	cellurphone = models.CharField(max_length = 20,blank = True)
	email = models.EmailField(max_length = 128, blank = True)
	address = models.CharField(max_length = 128, blank = True)
	memo = models.TextField(blank = True)
	# agency = models.ManyToManyField(User, related_name='agency_set')

	def __str__(self):
		return '{}'.format(self.customer_name,)

class Agency(models.Model):
	user = models.OneToOneField(User)
	agency_name = models.CharField(max_length = 60)
	def __str__(self):
		return '{}'.format(self.agency_name,)

materials/models.py
from django.db import models
from django.contrib.auth.models import User
from customers.models import Customer

import datetime

# Create your models here.
class Material(models.Model):
	customer = models.ForeignKey(Customer)
	material_name = models.CharField(max_length = 128)
	material_code = models.CharField(max_length = 20)
	control_code = models.CharField(max_length = 20)
	Pallet_unit = models.IntegerField(default = 1)
	Box_unit = models.IntegerField(default = 1)
	unit = models.CharField(max_length = 10, default = 'BOX')
	memo = models.TextField(blank = True)
	
	def __str__(self):
		return '{} ( {} [{}] )'.format(self.customer.customer_name,self.material_name,self.material_code)

class Zone(models.Model):
	zone = models.CharField(max_length = 20)

	def __str__(self):
		return self.zone

class Pallet(models.Model):
	pallet = models.CharField(max_length = 20)
	zone = models.ForeignKey(Zone)

	def __str__(self):
		return self.pallet

class Unit(models.Model):
	unit_code = models.CharField(max_length = 10)
	
	def __str__(self):
		return self.unit_code

class Packing(models.Model):
	Packing_code = models.CharField(max_length = 10)
	
	def __str__(self):
		return self.Packing_code

class Incoming(models.Model):
	pallet = models.ForeignKey(Pallet)
	material = models.ForeignKey(Material)
	incoming_date = models.DateTimeField(default = datetime.datetime.now)
	incoming_unit = models.ForeignKey(Unit)
	incoming_count = models.IntegerField(default = 0)
	unpackBox_count = models.IntegerField(default = 0)

	def __str__(self):
		return '{} {} {}'.format(self.incoming_date, self.pallet, self.material)

class Outgoing(models.Model):
	pallet = models.ForeignKey(Pallet)
	material = models.ForeignKey(Material)
	outgoing_date = models.DateTimeField(default = datetime.datetime.now)
	outgoing_unit = models.ForeignKey(Unit)
	packing = models.ForeignKey(Packing)
	outgoing_count = models.IntegerField(default = 0)
	unpackBox_count = models.IntegerField(default = 0)
	
	def __str__(self):
		return '{} {}'.format(self.outgoing_date, self.material)

materials/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

# class outgoingForm(forms.Form):
# 	zone = forms.CharField(label = 'Zone ID', max_length = 20)
# 	pallet = forms.CharField(label = 'Pallet ID', max_length = 20)
# 	material_code = forms.CharField(label ='Material Code', max_length = 20)
# 	unit = forms.CharField(label ='Unit', max_length = 10)
# 	count = forms.IntegerField(label ='Count')

class incomingForm(ModelForm):
	class Meta:
		model = Incoming
		fields = {'pallet', 'material', 'incoming_date', 'incoming_unit', 'incoming_count', 'unpackBox_count'}

class outgoingForm(ModelForm):
	class Meta:
		model = Outgoing
		fields = {'pallet', 'material', 'outgoing_date', 'outgoing_unit', 'packing', 'outgoing_count', 'unpackBox_count'}

materials/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib.auth.models import User
from django.db.models import Sum

from django.views.generic.edit import FormView

# Create your views here.
from .models import *
from customers.models import *
from .forms import *

def index(request):
	try:
		material_list = Material.objects.all().order_by('material_name').order_by('customer')
	except:
		raise Http404('Nothing material')
	context = {'material_list': material_list, 'customer':'Total',}
	return render(request, 'materials/index.html', context)

def index_detail(request, customer_id):
	try:
		customer = Customer.objects.get(id=customer_id)
	except:
		raise Http404('Nothing material')
	material_list = customer.material_set.all().order_by('material_name')
	context = {'material_list': material_list,'customer':customer}
	return render(request, 'materials/index.html', context)

def incoming(request):
	try:
		incoming_list = Incoming.objects.all().order_by('-incoming_date')
	except:
		raise Http404('Nothing information')
	context = {'incoming_list':incoming_list}
	return render(request, 'materials/incoming.html', context)

def incoming_material(request, material_id):
	try:
		material = Material.objects.get(id=material_id)
	except:
		raise Http404('Nothing information')
	incoming_list = material.incoming_set.all().order_by('-incoming_date')
	context = {'incoming_list':incoming_list}
	return render(request, 'materials/incoming.html', context)

def incoming_pallet(request, pallet_id):
	try:
		pallet = Pallet.objects.get(id=pallet_id)
	except:
		raise Http404('Nothing information')
	incoming_list = pallet.incoming_set.all().order_by('-incoming_date')
	context = {'incoming_list':incoming_list}
	return render(request, 'materials/incoming.html', context)

def incoming_zone(request, zone_id):
	try:
		zone = Zone.objects.get(id = zone_id)
		pallets = zone.pallet_set.all()
	except:
		raise Http404('Nothing information')
	pallet_id = []
	for pallet in pallets:
		pallet_id.append(pallet.id)
	incoming_list = []
	for id in pallet_id:
		incoming = Incoming.objects.filter(pallet_id = id)
		incoming_list += incoming
	context = {'incoming_list':incoming_list}
	return render(request, 'materials/incoming.html', context)

def incoming_customer(request, customer_id):
	try:
		customer = Customer.objects.get(id=customer_id)
		materials = customer.material_set.all()
	except:
		raise Http404('Nothing information')
	material_id =[]
	for material in materials:
		material_id.append(material.id)
	incoming_list = []
	for id in material_id:
		incoming = Incoming.objects.filter(material_id=id)
		incoming_list += incoming
	context = {'incoming_list':incoming_list}
	return render(request, 'materials/incoming.html', context)

def outgoing(request):
	try:
		outgoing_list = Outgoing.objects.all().order_by('-outgoing_date')
	except:
	 	raise Http404('Nothing information')
	context = {'outgoing_list':outgoing_list}
	return render(request, 'materials/outgoing.html', context)

def outgoing_material(request, material_id):
	try:
		material = Material.objects.get(id=material_id)
	except:
		raise Http404('Nothing information')
	outgoing_list = material.outgoing_set.all().order_by('-outgoing_date')
	context = {'outgoing_list':outgoing_list}
	return render(request, 'materials/outgoing.html', context)

def outgoing_pallet(request, pallet_id):
	try:
		pallet = Pallet.objects.get(id=pallet_id)
	except:
		raise Http404('Nothing information')
	outgoing_list = pallet.outgoing_set.all().order_by('-outgoing_date')
	context = {'outgoing_list':outgoing_list}
	return render(request, 'materials/outgoing.html', context)

def outgoing_zone(request, zone_id):
	try:
		zone = Zone.objects.get(id = zone_id)
		pallets = zone.pallet_set.all()
	except:
		raise Http404('Nothing information')
	pallet_id = []
	for pallet in pallets:
		pallet_id.append(pallet.id)
	outgoing_list = []
	for id in pallet_id:
		outgoing = Outgoing.objects.filter(pallet_id = id).order_by('-outgoing_date')
		outgoing_list += outgoing
	context = {'outgoing_list':outgoing_list}
	return render(request, 'materials/outgoing.html', context)

def outgoing_customer(request, customer_id):
	try:
		customer = Customer.objects.get(id=customer_id)
		materials = customer.material_set.all()
	except:
		raise Http404('Nothing information')
	material_id =[]
	for material in materials:
		material_id.append(material.id)
	outgoing_list = []
	for id in material_id:
		outgoing = Outgoing.objects.filter(material_id=id).order_by('-outgoing_date')
		outgoing_list += outgoing
	context = {'outgoing_list':outgoing_list}
	return render(request, 'materials/outgoing.html', context)
	
def result(request, customer_id=''):
	if customer_id == '':
		material_list = Material.objects.all()
	else:
		try:
			customer = Customer.objects.get(id=customer_id)
			material_list = customer.material_set.all()
		except:
			raise Http404('Nothing information')
	packing_list = Packing.objects.all()
	unit_list = Unit.objects.all()
	material_result = []
	for material in material_list:
		result={}
		result['customer'] = material.customer
		result['material_id'] = material.id
		result['material_name'] = material.material_name
		result['material_code'] = material.material_code
		result['control_code'] = material.control_code
		incoming_unpack_box_counts = Incoming.objects.filter(material_id=material.id).aggregate(Sum('unpackBox_count'))
		outgoing_unpack_box_counts = Outgoing.objects.filter(material_id=material.id).aggregate(Sum('unpackBox_count'))
		if (incoming_unpack_box_counts['unpackBox_count__sum'] or outgoing_unpack_box_counts['unpackBox_count__sum']):
			if (incoming_unpack_box_counts['unpackBox_count__sum'] and outgoing_unpack_box_counts['unpackBox_count__sum']):
				result['unpacking_Box'] = incoming_unpack_box_counts['unpackBox_count__sum'] + outgoing_unpack_box_counts['unpackBox_count__sum']
			elif incoming_unpack_box_counts['unpackBox_count__sum']:
				result['unpacking_Box'] = incoming_unpack_box_counts['unpackBox_count__sum']
			else:
				result['unpacking_Box'] = outgoing_unpack_box_counts['unpackBox_count__sum']
		count_result = {}
		for unit in unit_list:
			incoming_counts = Incoming.objects.filter(material_id=material.id, incoming_unit_id=unit.id).aggregate(Sum('incoming_count'))
			outgoing_counts = Outgoing.objects.filter(material_id=material.id, outgoing_unit_id=unit.id).aggregate(Sum('outgoing_count'))
			if (incoming_counts['incoming_count__sum'] or outgoing_counts['outgoing_count__sum']):
				if ( incoming_counts['incoming_count__sum'] and outgoing_counts['outgoing_count__sum'] ):
					count_result[unit.unit_code] = incoming_counts['incoming_count__sum'] - outgoing_counts['outgoing_count__sum']
				elif incoming_counts['incoming_count__sum']:
					count_result[unit.unit_code] = incoming_counts['incoming_count__sum']
				else:
					count_result[unit.unit_code] = int('-'+str(outgoing_counts['outgoing_count__sum']))
			else :
				count_result[unit.unit_code] = 0
		result['TTL_PALLET'] = count_result['PALLET']
		result['TTL_BOX'] = (result['TTL_PALLET'] * material.Pallet_unit) + count_result['BOX']
		result['TTL_EA'] = (result['TTL_BOX'] * material.Box_unit) + count_result['EA']
		material_result.append(result)
	if customer_id == '':
		context = {'material_result':material_result, 'customer':'Total'}
	else:
		# context = {'material_result':material_result, 'customer':customer}
		context = {'material_result':material_result}
	return render(request, 'materials/result.html', context)

def result_detail(request, material_id=''):
	if material_id == '':
		material = Material.objects.all()
	else:
		try:
			material = Material.objects.get(id=material_id)
		except:
			raise Http404('Nothing information')
	packing_list = Packing.objects.all()
	unit_list = Unit.objects.all()
	pallets = Pallet.objects.all()
	pallet_list = []
	for pallet in pallets:
		if Incoming.objects.filter(material_id=material_id, pallet_id=pallet.id) or Outgoing.objects.filter(material_id=material_id, pallet_id=pallet.id):
			pallet_list.append(pallet.id)
	detail_result = []
	for pallet in pallet_list:
		result={}
		result['customer'] = material.customer
		result['material_name'] = material.material_name
		result['material_code'] = material.material_code
		result['control_code'] = material.control_code
		result['pallet'] = Pallet.objects.get(pk=pallet).pallet
		result['zone'] = Pallet.objects.get(pk=pallet).zone
		incoming_unpack_box_counts = Incoming.objects.filter(material_id=material_id, pallet_id=pallet).aggregate(Sum('unpackBox_count'))
		outgoing_unpack_box_counts = Outgoing.objects.filter(material_id=material_id, pallet_id=pallet).aggregate(Sum('unpackBox_count'))
		if (incoming_unpack_box_counts['unpackBox_count__sum'] or outgoing_unpack_box_counts['unpackBox_count__sum']):
			if (incoming_unpack_box_counts['unpackBox_count__sum'] and outgoing_unpack_box_counts['unpackBox_count__sum']):
				result['unpacking_Box'] = incoming_unpack_box_counts['unpackBox_count__sum'] + outgoing_unpack_box_counts['unpackBox_count__sum']
			elif incoming_unpack_box_counts['unpackBox_count__sum']:
				result['unpacking_Box'] = incoming_unpack_box_counts['unpackBox_count__sum']
			else:
				result['unpacking_Box'] = outgoing_unpack_box_counts['unpackBox_count__sum']
		count_result = {}
		for unit in unit_list:
			incoming_counts = Incoming.objects.filter(material_id=material_id, pallet_id=pallet, incoming_unit_id=unit.id).aggregate(Sum('incoming_count'))
			outgoing_counts = Outgoing.objects.filter(material_id=material_id, pallet_id=pallet, outgoing_unit_id=unit.id).aggregate(Sum('outgoing_count'))
			if (incoming_counts['incoming_count__sum'] or outgoing_counts['outgoing_count__sum']):
				if ( incoming_counts['incoming_count__sum'] and outgoing_counts['outgoing_count__sum'] ):
					count_result[unit.unit_code] = incoming_counts['incoming_count__sum'] - outgoing_counts['outgoing_count__sum']

materials/templates/materials/incoming.html
{% extends "materials/layout.html" %}
{% block content %}
<body>
	<!--<h1>{{Date}} Incoming List</h1>-->
	<div class=" h2 home-title color2 acenter">{{Date}} 입고 목록</div>
	<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<td><B>선택</B></td>
				<td><B>입고 날짜</B></td>
				<td><B>화주명</B></td>
				<td><B>자재명</B></td>
				<td><B>자재코드</B></td>
				<td><B>관리코드</B></td>
				<td><B>위치코드</B></td>
				<td><B>팔레트코드</B></td> 
				<td><B>입고단위</B></td>
				<td><B>입고개수</B></td>
				<td><B>수정</B></td>
			</tr>
		</thead>
		<tbody>
		{% for incoming in incoming_list %}
			<tr>
				<td> <form actionc=""><input type="checkbox" name="select" value={{incoming.id}}></td>
				<td> {{incoming.incoming_date.year}}/{{incoming.incoming_date.month}}/{{incoming.incoming_date.day}}</td>
				<td> <a href="c{{incoming.material.customer.id}}"> {{incoming.material.customer}}</a></td>
				<td> <a href="m{{incoming.material.id}}"> {{incoming.material.material_name}}</a></td>
				<td> {{incoming.material.material_code}} </td>
				<td> {{incoming.material.control_code}} </td>
				<td> <a href="z{{incoming.pallet.zone.id}}">{{incoming.pallet.zone}}</a></td>
				<td> <a href="p{{incoming.pallet.id}}"> {{incoming.pallet}}</a></td>
				<td> {{incoming.incoming_unit}} </td>
				<td> {{incoming.incoming_count}} </td>
				<td> <a class="btn btn-default" href="edit{{incoming.pk}}"><span class="glyphicon glyphicon-pencil"></span></a> </td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	</div>
</body>
{% endblock %}

materials/templates/materials/incoming_form.html
{% extends "materials/layout.html" %}
{% block content %}
<body>
    <!--<h1>{{Date}} Incoming Work</h1>-->
    <div class=" h2 home-title color2 acenter">{{Date}} 입고 작업</div>
    <div class="table-responsive">
        <form action="" method = "post">
            <table class="table table-striped">
                {% csrf_token %}
                {{form.as_table}}
            </table>
            <button type="submit", class="btn btn-primary">확인</button>
        </form>
    </div>
</body>
{% endblock %}

materials/templates/materials/index.html
{% extends "materials/layout.html" %}

<html>
	{% block content %}

	<body>
		<!--<h1>{{customer}} 자재 목록</h1>-->
		<div class=" h2 home-title color2 acenter">{{customer}} 자재 목록</div>
		<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>화주명</B></td>
					<td><B>자재명</B></td>
					<td><B>자재코드</B></td>
					<td><B>관리코드</B></td>
					<td><B>관리단위</B></td>
					<td><B>박스(낱개)</B></td>
				</tr>
			</thead>
			<tbody>
			{% for material in material_list %}
				<tr>
					{% if customer == 'Total' %}
					<td>
					<a href="c/{{material.customer.id}}/">{{material.customer}}</a> </td>
					{% else %}
					<td> {{material.customer}} </td>
					{% endif %}
					<td> {{material.material_name}} </td>
					<td> {{material.material_code}} </td>
					<td> {{material.control_code}} </td>
					<td> {{material.unit}} </td>
					<td> {{material.Box_unit}} </td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		</div>
	</body>
	{% endblock %}
</html>

materials/templates/materials/layout___.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <title>(주)우창물류 자재관리</title>
        <link href="{% static 'materials/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'materials/bootstrap/css/bootstrap-responsive.css' %}" rel="stylesheet">
    </head>
    <body>
        <script type="text/javascript"
         src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
        </script>
        <script src="{% static 'materials/bootstrap/js/bootstrap.js' %}"></script>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <a class="brand" href="">(주)우창물류 자재관리</a>
                    <div class="nav-collapse in collapse" style="height: Opx;">
                        <ul class="nav">
                            <li class=""><a href="#">Education</a></li>
                            <li class=""><a href="#">Work Experience</a></li>
                            <li class=""><a href="#">Interests</a></li>
                            <li class=""><a href="#">Portfolios</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}
    </body>
</html>

materials/templates/materials/outgoing.html
{% extends "materials/layout.html" %}

<html> 

    {% block content %}
	<body>
		<!--<h1>{{Date}} Outgoing List</h1>-->
		<div class=" h2 home-title color2 acenter">{{Date}} 출고 목록</div>
    	<div class="table-responsive">
        
        <table class="table table-striped">
	        <thead>
	            <tr>
					<td><B>선택</B></td>
					<td><B>출고 날짜</B></td>
	            	<td><B>화주명</B></td>
	                <td><B>자재명</B></td>
	                <td><B>자재코드</B></td>
	                <td><B>관리코드</B></td>
					<td><B>위치코드</B></td>
					<td><B>팔레트코드</B></td> 
	                <td><B>출하단위</B></td>
					<td><B>포장관리</B></td>
					<td><B>출하개수</B></td>
					<td><B>수정</B></td>
	            </tr>
	        </thead>
            <tbody>
				{% for outgoing in outgoing_list %}
				<tr>
					<td> <form actionc=""><input type="checkbox" name="select" value={{outgoing.id}}></td>
					<td> {{outgoing.outgoing_date.year}}/{{outgoing.outgoing_date.month}}/{{outgoing.outgoing_date.day}}</td>
					<td> <a href="c{{outgoing.material.customer.id}}">{{outgoing.material.customer}}</a></td>
					<td> <a href="m{{outgoing.material.id}}"> {{outgoing.material.material_name}}</a></td>
					<td> {{outgoing.material.material_code}} </td>
					<td> {{outgoing.material.control_code}} </td>
					<td> <a href="z{{outgoing.pallet.zone.id}}">{{outgoing.pallet.zone}}</a></td>
					<td> <a href="p{{outgoing.pallet.id}}"> {{outgoing.pallet}}</a></td>
					<td> {{outgoing.outgoing_unit}} </td>
					{% if outgoing.unpackBox_count %}
					<td> {{outgoing.packing}}({{outgoing.unpackBox_count}}) </td>
					{% else %}
					<td> {{outgoing.packing}} </td>
					{% endif %}
					<td> {{outgoing.outgoing_count}} </td>
					<td> <a class="btn btn-default" href="edit{{outgoing.pk}}"><span class="glyphicon glyphicon-pencil"></span></a> </td>
				</tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </body>
    {% endblock %}
</html>

materials/templates/materials/outgoing_detail.html
<!-- {% extends "materials/layout.html" %}
{% load staticfiles %}
{% block content %} -->
<!--<h1>{{ customer.id }}</h1>-->
<div class=" h2 home-title color2 acenter">{{ customer.id }}</div>

<!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->
<form action="{% url 'materials:outsubmit' customer %}" method="post">
{% csrf_token %}
{% for customer in material_list.customer_set.all %}
	<input type="radio" name="choice" id="customer{{ forloop.counter }}" value="{{ customer.id }}">
	<label for="customer{{ forloop.counter }}">{{ customer.id }}</label>
{% endfor %}
</form>
<!-- <label for =  -->
<!-- {% endblock %}

materials/templates/materials/outgoing_form.html
{% extends "materials/layout.html" %}
{% block content %}
<body>
    <!--<h1>{{Date}} Outgoing Work</h1>-->
    <div class=" h2 home-title color2 acenter">{{Date}} 출고 작업</div>
    <div class="table-responsive">
        <form action="" method = "post">
            <table class="table table-striped">
                {% csrf_token %}
                {{form.as_table}}
            </table>
            <button type="submit", class="btn btn-primary">확인</button>
        </form>
    </div>
</body>
{% endblock %}

materials/templates/materials/result.html
{% extends "materials/layout.html" %}
{% load staticfiles %}
{% block content %}
	<body>
		<!--<h1>{{customer}} Count Result List</h1>-->
		<div class=" h2 home-title color2 acenter">{{customer}} 자재 처리 목록</div>
		<div class="table-responsive">

		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>화주명</B></td>
					<td><B>자재명</B></td>
					<td><B>자재코드</B></td>
					<td><B>관리코드</B></td>
					<td><B>총 박스 개수</B></td>
					<td><B>총 낱개 개수</B></td>
					<!-- <td><B>Packing Box Count</B></td> -->
					<td><B>개봉박스 개수</B></td>
				</tr>
			</thead>
			<tbody>
				{% for result in material_result %}
				<tr>
					{% if customer == 'Total' %}
					<td> <a href="c{{result.customer.id}}/">{{result.customer}}</a> </td>
					<td> <a href="m{{result.material_id}}/">{{result.material_name}}</a> </td>
					{% else %}
					<td> {{result.customer}} </td>
					<td> {{result.material_name}} </td>
					{% endif %}
					<td> {{result.material_code}} </td>
					<td> {{result.control_code}} </td>
					{% if result.unpacking_Box %}
					<td> {{result.TTL_BOX}}({{result.unpacking_Box}}) </td>
					{% else %}
					<td> {{result.TTL_BOX}} </td>
					{% endif %}
					<td> {{result.TTL_EA}} </td>
					<!-- <td> {{result.packing_box}} </td> -->
					<td> {{result.unpacking_Box}} </td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		</div>
	</body>
{% endblock %}

materials/templates/materials/result_detail.html
{% extends "materials/layout.html" %}
{% load staticfiles %}
{% block content %}
	<body>
		<!--<h1>{{material}} Count Result List</h1>-->
		<div class=" h2 home-title color2 acenter">{{material}} 자재 처리 세부 목록</div>
		<div class="table-responsive">

		<table class="table table-striped">
			<thead>
				<tr>
					<td><B>화주명</B></td>
					<td><B>자재명</B></td>
					<td><B>자재코드</B></td>
					<td><B>관리코드</B></td>
					<td><B>위치코드</B></td>
					<td><B>팔레트코드</B></td> 
					<td><B>총 박스 개수</B></td>
					<td><B>총 낱개 개수</B></td>
					<!-- <td><B>Packing Box Count</B></td> -->
					<td><B>개봉박스 개수</B></td>
				</tr>
			</thead>
			<tbody>
				{% for result in detail_result %}
				<tr>
					<td> {{result.customer}} </td>
					<td> {{result.material_name}} </td>
					<td> {{result.material_code}} </td>
					<td> {{result.control_code}} </td>
					<td> {{result.zone}} </td>
					<td> {{result.pallet}} </td>
					{% if result.unpacking_Box %}
					<td> {{result.TTL_BOX}}({{result.unpacking_Box}}) </td>
					{% else %}
					<td> {{result.TTL_BOX}} </td>
					{% endif %}
					<td> {{result.TTL_EA}} </td>	
					<!-- <td> {{result.packing_box}} </td> -->
					<td> {{result.unpacking_Box}} </td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		</div>
	</body>
{% endblock %}